language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'
script:
  - yarn lint
  - yarn run tsc --noEmit
branches:
  only: master
notifications:
  email: false
