language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script:
  - yarn run test --ci --detectOpenHandles
branches:
  only: master
notifications:
  email: false
